y=[2,4,6,2,4,8,10,4,12,16]
print("Given list")
print(y)
a=y.count(4)
print("number of times 4 is found=",a)
print("reversed order")
y.reverse()
print(y)
y.sort()
print("sorted list")
print(y)
d=max(y)
e=min(y)
print("max value of list =",d)
print("min value of list =",e)
